#!/usr/bin/env python
from datetime import datetime

if __name__ == '__main__':
    r"""
    This script is used to display the date in the format I need for typesetting lecture notes in
    LaTeX.

    See ~/.config/nvim/init.vim
    """
    curr_date = datetime.today()
    months = {
        1: "January",
        2: "February",
        3: "March",
        4: "April",
        5: "May",
        6: "June",
        7: "July",
        8: "August",
        9: "September",
        10: "October",
        11: "November",
        12: "December"
    }
    print(curr_date.day, months[curr_date.month], curr_date.year)

