#!/usr/bin/env python
import argparse
import numpy as np


def transform(args):
    body = list(args.txt)
    p = np.random.binomial(size=len(body), n=1, p=0.55)
    for idx, char in enumerate(body):
        body[idx] = char.upper() if p[idx] == 1 else char.lower()
    return ''.join(body)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Meme my text')
    parser.add_argument('--txt', type=str)
    args = parser.parse_args()
    results = [transform(args), transform(args), transform(args)]
    print('Sample 1:', results[0])
    print('Sample 2', results[1])
    print('Sample 3', results[2])


